DELETE FROM BusinessArea;
DELETE FROM SurveyQuestion;
INSERT INTO BusinessArea (id, status, name) VALUES
(1, 1, 'Cibersegurança'),
(2, 1, 'Criptomoedas'),
(3, 1, 'Gestão de TI'),
(4, 1, 'Dados'),
(5, 1, 'Programação'),
(6, 1, 'Design/Jogos Digitais'),
(7, 1, 'Inteligência Artificial');
INSERT INTO SurveyQuestion (id, status, description, survey_id, `order` ) VALUES
(1, 1, 'Você está organizando uma festa e precisa criar um guia com os horários de todas as atraçoes e  atividades. Como você faria isso?', 1, 1),
(2, 1, 'Você está planejando uma viagem e precisa pesquisar diferentes destinos, levando em consideração clima, preço, atrações e avaliações. Como organizaria e compararia essas informações?', 1, 2),
(3, 1, 'Você está em um local desconhecido e encontra uma caixa cheia de moedas antigas de diferentes países. Como descobriria o valor dessas moedas e se elas valem algo atualmente?', 1, 3),
(4, 1, 'Você é um detetive e precisa resolver um crime. Como organizaria as pistas e deduziria o que aconteceu?', 1, 4),
(5, 1, 'Você é um chef de cozinha e precisa criar um novo prato para o cardápio do seu restaurante. Como pesquisaria ingredientes, combinaria sabores e testaria diferentes receitas?', 1, 5),
(6, 1, 'Você está liderando uma equipe em um projeto importante. Como coordenaria a equipe e garantiria que todos estejam alinhados e contribuindo para o sucesso do projeto?', 1, 6),
(7, 1, 'Como arquiteto, qual recurso tecnológico implementaria para garantir segurança e eficiência no projeto de uma casa moderna?', 1, 7),
(8, 1, 'Você está participando de um hackathon e precisa criar uma solução inovadora em um curto espaço de tempo. Como você e sua equipe dividiriam as tarefas e desenvolveriam a solução?', 1, 8),
(9, 1, 'Você e seus amigos decidem criar um novo jogo de tabuleiro. Como você abordaria o processo de desenvolvimento do jogo, desde a concepção até a produção final?', 1, 9),
(10, 1, 'Você está montando uma playlist para uma festa, mas quer que as músicas sejam reproduzidas em uma ordem específica para criar a melhor atmosfera possível ao longo da noite. Como você organizaria a sequência das músicas?', 1, 10),
(11, 1, 'Você precisa organizar uma mudança para uma nova casa e quer garantir que tudo seja embalado e transportado de forma eficiente. Como você faria isso?', 1, 11),
(12, 1, 'Você precisa criar uma apresentação para um projeto importante e deseja que ela seja envolvente e fácil de entender. Como você abordaria a criação da apresentação?', 1, 12);
INSERT INTO SurveyAnswer (id, status, description, `order` , survey_question_id, business_area_id) VALUES
(1, 1, 'a) Montaria um plano flexível, com atividades principais, adaptando-o conforme o ritmo e interesse dos convidados.', 1, 1, 1),
(2, 1, 'b) Desenharia um mapa da festa, mostrando como os convidados e atividades se organizam.', 2, 1, 2),
(3, 1, 'c) Criaria um cronograma de projeto utilizando técnicas de gestão para garantir que tudo ocorra conforme o planejado.', 3, 1, 3),
(4, 1, 'd) Utilizaria um aplicativo de produtividade, configurando lembretes automáticos e monitorando o progresso das atividades.', 4, 1, 4),
(5, 1, 'e) Criaria uma programação detalhada, semelhante a um roteiro de filme, definindo cenas e horários específicos para cada atividade.', 5, 1, 5),
(6, 1, 'f) Planejaria uma experiência temática, desenhando convites e decorações para envolver os convidados.', 6, 1, 6),
(7, 1, 'g) Desenvolveria uma forma de ajustar as atividades da festa em tempo real, com base nas atrações que os convidados mais estão curtindo.', 7, 1, 7),
(8, 1, 'a) Pesquisaria em blogs de viagem e fóruns, criando um diário de viagem virtual com opiniões e experiências coletadas.', 1, 2, 1),
(9, 1, 'b) Consultaria guias e pacotes turísticos para formar uma visão abrangente de cada destino.', 2, 2, 2),
(10, 1, 'c) Criaria um plano de viagem utilizando uma ferramenta de gestão, com cronograma e orçamento detalhados.', 3, 2, 3),
(11, 1, 'd) Criaria uma lista com notas para cada destino, destacando vantagens e desvantagens.', 4, 2, 4),
(12, 1, 'e) Desenvolveria um mapa interativo onde cada destino pode ser clicado para obter informações detalhadas.', 5, 2, 5),
(13, 1, 'f) Desenvolveria uma apresentação visual dos destinos, com fotos, vídeos e descrições envolventes.', 6, 2, 6),
(14, 1, 'g) Usaria a inteligência artificial para otimizar esse processo.', 7, 2, 7),
(15, 1, 'a) Utilizaria um aplicativo de reconhecimento de moedas com inteligência artificial para obter uma identificação e avaliação rápida.', 1, 3, 1),
(16, 1, 'b) Pesquisaria a história e o contexto das moedas utilizando livros antigos, visitas a museus e sites especializados.', 2, 3, 2),
(17, 1, 'c) Organizaria um projeto de pesquisa detalhado para catalogar e avaliar as moedas.', 3, 3, 3),
(18, 1, 'd) Levaria as moedas a um especialista em numismática para uma avaliação detalhada e precisa de seu valor no mercado atual.', 4, 3, 4),
(19, 1, 'e) Participaria de fóruns e comunidades online de colecionadores de moedas, comparando suas descobertas.', 5, 3, 5),
(20, 1, 'f) Desenvolveria uma aplicação interativa que permite explorar as moedas e suas histórias.', 6, 3, 6),
(21, 1, 'g) Usaria a inteligência artificial para reconhecer cada uma das moedas por meio de reconhecimento de imagens.', 7, 3, 7),
(22, 1, 'a) Entrevistaria testemunhas e compararia seus depoimentos minuciosamente, buscando inconsistências e informações cruciais.', 1, 4, 1),
(23, 1, 'b) Recriaria a linha do tempo dos eventos usando gráficos e recursos visuais, para entender a sequência e o contexto do crime.', 2, 4, 2),
(24, 1, 'c) Gerenciaria as pistas e a investigação utilizando um software de organização.', 3, 4, 3),
(25, 1, 'd) Criaria um sistema de classificação para organizar as pistas por tipo, data e local de coleta, facilitando a análise.', 4, 4, 4),
(26, 1, 'e) Desenvolveria um diagrama interativo com todas as pistas, conectando-as e destacando padrões e possíveis suspeitos.', 5, 4, 5),
(27, 1, 'f) Escreveria um relato detalhado dos eventos, ilustrando cada etapa da investigação com imagens e diagramas.', 6, 4, 6),
(28, 1, 'g) Utilizaria um sistema de inteligência artificial para analisar as pistas e sugerir possíveis soluções com base em padrões e probabilidades.', 7, 4, 7),
(29, 1, 'a) Organizaria sessões de degustação com um grupo de clientes selecionados, coletando feedback detalhado para aperfeiçoar a receita.', 1, 5, 1),
(30, 1, 'b) Criaria um mapa de sabores, destacando como diferentes ingredientes se complementam ou contrastam, para guiar suas combinações.', 2, 5, 2),
(31, 1, 'c) Usaria técnicas de gestão de projetos para planejar, testar e aperfeiçoar a receita, assegurando a eficiência no processo.', 3, 5, 3),
(32, 1, 'd) Consultaria uma ampla gama de livros de culinária, blogs e vídeos de chefs renomados para inspiração e novas ideias.', 4, 5, 4),
(33, 1, 'e) Experimentaria diversas combinações de ingredientes, documentando cada teste em um diário de receitas, ajustando até alcançar a perfeição.', 5, 5, 5),
(34, 1, 'f) Desenvolveria uma apresentação visual do prato, incluindo detalhes para torná-lo mais bonito e interessante.', 6, 5, 6),
(35, 1, 'g) Usaria um modelo de inteligência artificial para sugerir combinações de ingredientes e prever o sucesso do prato com base em dados anteriores.', 7, 5, 7),
(36, 1, 'a) Realizaria reuniões regulares para compartilhar atualizações e resolver problemas em equipe, incentivando a comunicação aberta.', 1, 6, 1),
(37, 1, 'b) Estabeleceria um sistema de recompensas para incentivar a produtividade e a inovação, reconhecendo as contribuições individuais.', 2, 6, 2),
(38, 1, 'c) Utilizaria uma ferramenta de gestão de projetos para definir tarefas, prazos e acompanhar o progresso.', 3, 6, 3),
(39, 1, 'd) Criaria um dashboard para monitorar o desempenho da equipe, identificando áreas de melhoria e ajustando estratégias conforme necessário.', 4, 6, 4),
(40, 1, 'e) Desenvolveria uma plataforma colaborativa onde todos podem compartilhar ideias, arquivos e feedbacks em tempo real.', 5, 6, 5),
(41, 1, 'f) Produziria materiais visuais e gráficos para ilustrar o progresso do projeto e motivar a equipe.', 6, 6, 6),
(42, 1, 'g) Utilizaria um sistema de inteligência artificial para prever e alertar sobre possíveis atrasos, sugerindo ajustes para manter o cronograma em dia.', 7, 6, 7),
(43, 1, 'a) Avaliaria possíveis pontos de vulnerabilidade na estrutura da casa e implementaria medidas de segurança em cada nível, como sistemas de alarme, câmeras de segurança e fechaduras inteligentes.', 1, 7, 1),
(44, 1, 'b) Analisaria as tendências de uso de tecnologias modernas e integraria eletrodomésticos inteligentes para gestão de serviços e manutenção da casa, aumentando a segurança e a transparência.', 2, 7, 2),
(45, 1, 'c) Aplicaria padrões de design reconhecidos para criar uma arquitetura modular e escalável, facilitando futuras expansões e manutenções da casa.', 3, 7, 3),
(46, 1, 'd) Implementaria um sistema de monitoramento contínuo para analisar o desempenho das instalações da casa, identificando e corrigindo problemas antes que se tornem críticos.', 4, 7, 4),
(47, 1, 'e) Utilizaria um sistema de gestão de projeto digital para coordenar todas as fases da construção, garantindo que cada etapa seja concluída de maneira eficiente e dentro do cronograma.', 5, 7, 5),
(48, 1, 'f) Criaria um modelo 3D detalhado da casa para visualizar e ajustar o design conforme necessário, otimizando a funcionalidade e o conforto do ambiente.', 6, 7, 6),
(49, 1, 'g) Implementaria um sistema de IA para otimizar o planejamento e o design da casa, ajustando automaticamente o layout e as especificações para maximizar a eficiência energética e a segurança com base em dados históricos e padrões de uso.', 7, 7, 7),
(50, 1, 'a) Faria uma rápida avaliação das habilidades de cada membro da equipe e distribuiria tarefas conforme suas especialidades.', 1, 8, 1),
(51, 1, 'b) Criaria um diagrama de fluxo para visualizar a solução final e identificar as etapas necessárias para implementá-la.', 2, 8, 2),
(52, 1, 'c) Utilizaria uma metodologia ágil para dividir as tarefas em sprints e realizar reuniões diárias de acompanhamento.', 3, 8, 3),
(53, 1, 'd) Configuraria um sistema de versionamento de código para que todos possam trabalhar de forma colaborativa e sem conflitos.', 4, 8, 4),
(54, 1, 'e) Desenvolveria um protótipo funcional que permita testar as principais funcionalidades da solução em um ambiente controlado.', 5, 8, 5),
(55, 1, 'f) Criaria uma apresentação visual impactante para demonstrar a solução e convencer os jurados da sua viabilidade.', 6, 8, 6),
(56, 1, 'g) Utilizaria uma inteligência artificial para analisar dados em tempo real, sugerindo ajustes e otimizações à medida que o projeto avança.', 7, 8, 7),
(57, 1, 'a) Organizaria sessões de teste com amigos e familiares para coletar feedback e ajustar as regras.', 1, 9, 1),
(58, 1, 'c) Desenvolveria um sistema de recompensas e desafios dentro do jogo para torná-lo mais envolvente.', 2, 9, 2),
(59, 1, 'b) Usaria técnicas de gestão de projetos para planejar e coordenar todas as etapas do desenvolvimento do jogo.', 3, 9, 3),
(60, 1, 'e) Faria uma pesquisa detalhada sobre outros jogos de tabuleiro para entender o que funciona bem e o que pode ser melhorado.', 4, 9, 4),
(61, 1, 'f) Criaria uma lista de regras e mecânicas do jogo, testando diferentes versões até encontrar a melhor.', 5, 9, 5),
(62, 1, 'd) Desenharia componentes visuais atraentes, incluindo o tabuleiro, cartas e peças, para melhorar a experiência do jogador.', 6, 9, 6),
(63, 1, 'g) Utilizaria técnicas de IA para simular partidas e ajustar o equilíbrio do jogo antes do lançamento.', 7, 9, 7),
(64, 1, 'd) Montaria a playlist com base em sugestões de amigos e familiares, organizando-a manualmente para garantir que todos aproveitem.', 1, 10, 1),
(65, 1, 'c) Desenharia a playlist como uma história musical, guiando a festa através de diferentes emoções e climas.', 2, 10, 2),
(66, 1, 'e) Utilizaria técnicas de gestão para planejar o fluxo da festa e organizar a playlist em blocos temáticos.', 3, 10, 3),
(67, 1, 'b) Analisaria as preferências musicais dos convidados e criaria gráficos para entender quais gêneros e estilos agradam mais.', 4, 10, 4),
(68, 1, 'a) Criaria uma lista de reprodução automatizada, utilizando um algoritmo para determinar a ordem das músicas com base no ritmo e popularidade.', 5, 10, 5),
(69, 1, 'f) Criaria uma apresentação visual sincronizada com as músicas, com efeitos e animações que acompanham o ritmo.', 6, 10, 6),
(70, 1, 'g) Utilizaria IA para analisar as características das músicas e criar uma sequência que maximize a energia da festa.', 7, 10, 7),
(71, 1, 'a) Planejaria um cronograma detalhado da mudança, com um dia específico para cada etapa.', 1, 11, 1),
(72, 1, 'b) Organizaria as caixas por cômodo e marcaria cada uma, criando um sistema de cores para facilitar o desempacotamento.', 2, 11, 2),
(73, 1, 'c) Criaria uma lista detalhada de todos os itens a serem embalados, organizando-os por categoria e prioridade.', 3, 11, 3),
(74, 1, 'd) Faria uma pesquisa sobre empresas de mudança, comparando preços e serviços para escolher a melhor opção.', 4, 11, 4),
(75, 1, 'e) Desenvolveria um aplicativo que ajudaria a rastrear o progresso da mudança e a localização de cada item.', 5, 11, 5),
(76, 1, 'f) Utilizaria um software de visualização para planejar a nova disposição dos móveis e itens na nova casa.', 6, 11, 6),
(77, 1, 'g) Utilizaria um modelo de IA para prever problemas potenciais durante a mudança e sugerir soluções antecipadamente.', 7, 11, 7),
(78, 1, 'a) Realizaria sessões de prática com colegas para garantir que a apresentação seja clara, envolvente e sem falhas.', 1, 12, 1),
(79, 1, 'b) Desenvolveria uma narrativa envolvente que guia a audiência através da apresentação com começo, meio e fim claros.', 2, 12, 2),
(80, 1, 'c) Organizaria os tópicos em um plano de projeto, criando uma estrutura lógica e cronológica para a apresentação.', 3, 12, 3),
(81, 1, 'd) Faria uma análise detalhada dos dados do projeto e apresentaria os resultados com gráficos e tabelas.', 4, 12, 4),
(82, 1, 'e) Criaria um protótipo interativo do projeto, permitindo que a audiência explore diferentes aspectos em tempo real.', 5, 12, 5),
(83, 1, 'f) Utilizaria um software de criação gráfica para projetar slides visualmente atraentes e interativos.', 6, 12, 6),
(84, 1, 'g) Utilizaria IA para ajustar a apresentação com base no feedback em tempo real, personalizando-a para diferentes tipos de audiência.', 7, 12, 7);