"""descrição da migração

Revision ID: 349e68891c1c
Revises: 
Create Date: 2025-04-06 12:40:55.347559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.infra.adapters.orm.database_schema import StatusType, DescriptionType, NameType, EmailType, CellPhoneType, QuestionDescriptionType


# revision identifiers, used by Alembic.
revision: str = '349e68891c1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BusinessArea',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('name', NameType(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Survey',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('name', NameType(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('name', NameType(length=100), nullable=False),
    sa.Column('email', EmailType(length=100), nullable=False),
    sa.Column('cell_phone', CellPhoneType(length=11), nullable=False),
    sa.Column('ethnicity', DescriptionType(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('female_gender', sa.Boolean(), nullable=False),
    sa.Column('password', EmailType(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SurveyQuestion',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('description', QuestionDescriptionType(length=8000), nullable=False),
    sa.Column('survey_id', sa.BigInteger(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['Survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_survey_question_survey_id', 'SurveyQuestion', ['survey_id'], unique=False)
    op.create_table('SurveyAnswer',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('description', QuestionDescriptionType(length=8000), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('survey_question_id', sa.BigInteger(), nullable=False),
    sa.Column('business_area_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['business_area_id'], ['BusinessArea.id'], ),
    sa.ForeignKeyConstraint(['survey_question_id'], ['SurveyQuestion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_survey_answer_business_area_id', 'SurveyAnswer', ['business_area_id'], unique=False)
    op.create_index('ix_survey_answer_question_id', 'SurveyAnswer', ['survey_question_id'], unique=False)
    op.create_table('UserSurveyAnswer',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('survey_id', sa.BigInteger(), nullable=False),
    sa.Column('survey_question_id', sa.BigInteger(), nullable=False),
    sa.Column('survey_answer_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['survey_answer_id'], ['SurveyAnswer.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['Survey.id'], ),
    sa.ForeignKeyConstraint(['survey_question_id'], ['SurveyQuestion.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_survey_answer_id', 'UserSurveyAnswer', ['survey_answer_id'], unique=False)
    op.create_index('ix_user_survey_answer_question_id', 'UserSurveyAnswer', ['survey_question_id'], unique=False)
    op.create_index('ix_user_survey_answer_survey_id', 'UserSurveyAnswer', ['survey_id'], unique=False)
    op.create_index('ix_user_survey_answer_user_id', 'UserSurveyAnswer', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_survey_answer_user_id', table_name='UserSurveyAnswer')
    op.drop_index('ix_user_survey_answer_survey_id', table_name='UserSurveyAnswer')
    op.drop_index('ix_user_survey_answer_question_id', table_name='UserSurveyAnswer')
    op.drop_index('ix_user_survey_answer_id', table_name='UserSurveyAnswer')
    op.drop_table('UserSurveyAnswer')
    op.drop_index('ix_survey_answer_question_id', table_name='SurveyAnswer')
    op.drop_index('ix_survey_answer_business_area_id', table_name='SurveyAnswer')
    op.drop_table('SurveyAnswer')
    op.drop_index('ix_survey_question_survey_id', table_name='SurveyQuestion')
    op.drop_table('SurveyQuestion')
    op.drop_table('User')
    op.drop_table('Survey')
    op.drop_table('BusinessArea')
    # ### end Alembic commands ###
