"""tamanho das perguntas e respostas

Revision ID: a6cc2dcd95d6
Revises: 48a353136185
Create Date: 2025-04-05 11:30:02.747652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.infra.adapters.orm.database_schema import StatusType, DescriptionType, NameType, EmailType, CellPhoneType, QuestionDescriptionType
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a6cc2dcd95d6'
down_revision: Union[str, None] = '48a353136185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SurveyAnswer', 'description',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=100),
               type_=QuestionDescriptionType(length=8000),
               existing_nullable=False)
    op.alter_column('SurveyQuestion', 'description',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=100),
               type_=QuestionDescriptionType(length=8000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SurveyQuestion', 'description',
               existing_type=QuestionDescriptionType(length=8000),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=100),
               existing_nullable=False)
    op.alter_column('SurveyAnswer', 'description',
               existing_type=QuestionDescriptionType(length=8000),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
