"""Initial migration

Revision ID: a6f575443f8e
Revises: 
Create Date: 2025-03-24 17:57:10.195162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.infra.adapters.orm.database_schema import StatusType, DescriptionType, NameType, EmailType, CellPhoneType


# revision identifiers, used by Alembic.
revision: str = 'a6f575443f8e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BusinessArea',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('name', NameType(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Survey',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('name', NameType(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('name', NameType(length=100), nullable=False),
    sa.Column('email', EmailType(length=100), nullable=False),
    sa.Column('cell_phone', CellPhoneType(length=11), nullable=False),
    sa.Column('ethnicity', DescriptionType(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('female_gender', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SurveyQuestion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('description', DescriptionType(length=100), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['Survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_survey_question_survey_id', 'SurveyQuestion', ['survey_id'], unique=False)
    op.create_table('SurveyAnswer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('description', DescriptionType(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('survey_question_id', sa.Integer(), nullable=False),
    sa.Column('business_area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_area_id'], ['BusinessArea.id'], ),
    sa.ForeignKeyConstraint(['survey_question_id'], ['SurveyQuestion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_survey_answer_business_area_id', 'SurveyAnswer', ['business_area_id'], unique=False)
    op.create_index('ix_survey_answer_question_id', 'SurveyAnswer', ['survey_question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_survey_answer_question_id', table_name='SurveyAnswer')
    op.drop_index('ix_survey_answer_business_area_id', table_name='SurveyAnswer')
    op.drop_table('SurveyAnswer')
    op.drop_index('ix_survey_question_survey_id', table_name='SurveyQuestion')
    op.drop_table('SurveyQuestion')
    op.drop_table('User')
    op.drop_table('Survey')
    op.drop_table('BusinessArea')
    # ### end Alembic commands ###
